POST http://localhost:5000/api/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName":"Delly",
    "email": "joyt@jhg.lhj",
    "password": "1236258",
    "gender": "female"
}